url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Edirom-Summer-School" # the name of your site, e.g. ACME Corp.
sass:
  load_paths:
    - _sass
    - node_modules/bootstrap/scss
  style: compressed

copy_to_dest:
  - source: node_modules/@fortawesome/fontawesome-free/webfonts/.
    target: assets/webfonts/
  - source: node_modules/@fortawesome/fontawesome-free/svgs/.
    target: assets/svgs/
  - source: node_modules/bootstrap/dist/js/bootstrap.min.js
    target: assets/js/
  - source: node_modules/jquery/dist/jquery.min.js
    target: assets/js/

collections:
  archiv:
    sort_by: title
    output: true
    permalink: /:path:output_ext

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "_archiv/*/programm.html"
    values:
      layout: "program"
  - scope:
      path: "_archiv/*/classes"
    values:
      requirements: "–"
      level: "any"
      lang: "deutsch"
      software: "–"
      costs: "–"
